name: CI/CD

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8

    - name: Run Black formatter check
      run: |
        black --check .

    - name: Run Flake8 linter
      run: |
        flake8 . --max-line-length=120 --exclude=.git,__pycache__,docs,build,dist,venv,archive,analysis,osparc_api_example,post_process_results,scripts,tests --ignore=E203,W503,E731,F401,F841

    - name: Run Pytest tests
      run: |
        export PYTHONPATH=$PYTHONPATH:./src
        pytest
