name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install linting dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==25.9.0 isort==5.13.2 flake8==7.0.0

    - name: Run linting checks
      run: |
        black --check --exclude 'archive/|analysis/|osparc_api_example/|post_process_results/' .
        isort --check --profile black --skip-glob 'archive/*' --skip-glob 'analysis/*' --skip-glob 'osparc_api_example/*' --skip-glob 'post_process_results/*' .
        flake8 --max-line-length=140 --extend-ignore=E203,W503 --exclude 'archive/,analysis/,osparc_api_example/,post_process_results/,docs/' .

    - name: Run Pytest tests
      run: |
        export PYTHONPATH=$PYTHONPATH:./src
        pytest -m "not skip_on_ci" tests/
